/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyCreateDto {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "permissions")]
    pub permissions: Vec<models::Permission>,
}

impl ApiKeyCreateDto {
    pub fn new(permissions: Vec<models::Permission>) -> ApiKeyCreateDto {
        ApiKeyCreateDto {
            name: None,
            permissions,
        }
    }
}

