/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyResponseDto {
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<models::Permission>,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl ApiKeyResponseDto {
    pub fn new(created_at: String, id: String, name: String, permissions: Vec<models::Permission>, updated_at: String) -> ApiKeyResponseDto {
        ApiKeyResponseDto {
            created_at,
            id,
            name,
            permissions,
            updated_at,
        }
    }
}

