/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetStackResponseDto {
    #[serde(rename = "assetCount")]
    pub asset_count: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "primaryAssetId")]
    pub primary_asset_id: String,
}

impl AssetStackResponseDto {
    pub fn new(asset_count: i32, id: String, primary_asset_id: String) -> AssetStackResponseDto {
        AssetStackResponseDto {
            asset_count,
            id,
            primary_asset_id,
        }
    }
}

