/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.111.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadUpdate {
    #[serde(rename = "archiveSize", skip_serializing_if = "Option::is_none")]
    pub archive_size: Option<i32>,
}

impl DownloadUpdate {
    pub fn new() -> DownloadUpdate {
        DownloadUpdate {
            archive_size: None,
        }
    }
}

