/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadResponse {
    #[serde(rename = "archiveSize")]
    pub archive_size: i32,
    #[serde(rename = "includeEmbeddedVideos")]
    pub include_embedded_videos: bool,
}

impl DownloadResponse {
    pub fn new(archive_size: i32, include_embedded_videos: bool) -> DownloadResponse {
        DownloadResponse {
            archive_size,
            include_embedded_videos,
        }
    }
}

