/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FoldersResponse {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "sidebarWeb")]
    pub sidebar_web: bool,
}

impl FoldersResponse {
    pub fn new(enabled: bool, sidebar_web: bool) -> FoldersResponse {
        FoldersResponse {
            enabled,
            sidebar_web,
        }
    }
}

