/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseKeyDto {
    #[serde(rename = "activationKey")]
    pub activation_key: String,
    #[serde(rename = "licenseKey")]
    pub license_key: String,
}

impl LicenseKeyDto {
    pub fn new(activation_key: String, license_key: String) -> LicenseKeyDto {
        LicenseKeyDto {
            activation_key,
            license_key,
        }
    }
}

