/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MapReverseGeocodeResponseDto {
    #[serde(rename = "city", deserialize_with = "Option::deserialize")]
    pub city: Option<String>,
    #[serde(rename = "country", deserialize_with = "Option::deserialize")]
    pub country: Option<String>,
    #[serde(rename = "state", deserialize_with = "Option::deserialize")]
    pub state: Option<String>,
}

impl MapReverseGeocodeResponseDto {
    pub fn new(city: Option<String>, country: Option<String>, state: Option<String>) -> MapReverseGeocodeResponseDto {
        MapReverseGeocodeResponseDto {
            city,
            country,
            state,
        }
    }
}

