/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemoriesResponse {
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl MemoriesResponse {
    pub fn new(enabled: bool) -> MemoriesResponse {
        MemoriesResponse {
            enabled,
        }
    }
}

