/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.111.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PartnerDirection {
    #[serde(rename = "shared-by")]
    By,
    #[serde(rename = "shared-with")]
    With,

}

impl std::fmt::Display for PartnerDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::By => write!(f, "shared-by"),
            Self::With => write!(f, "shared-with"),
        }
    }
}

impl Default for PartnerDirection {
    fn default() -> PartnerDirection {
        Self::By
    }
}

