/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.111.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeopleResponseDto {
    /// This property was added in v1.110.0
    #[serde(rename = "hasNextPage", skip_serializing_if = "Option::is_none")]
    pub has_next_page: Option<bool>,
    #[serde(rename = "hidden")]
    pub hidden: i32,
    #[serde(rename = "people")]
    pub people: Vec<models::PersonResponseDto>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl PeopleResponseDto {
    pub fn new(hidden: i32, people: Vec<models::PersonResponseDto>, total: i32) -> PeopleResponseDto {
        PeopleResponseDto {
            has_next_page: None,
            hidden,
            people,
            total,
        }
    }
}

