/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.111.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurchaseUpdate {
    #[serde(rename = "hideBuyButtonUntil", skip_serializing_if = "Option::is_none")]
    pub hide_buy_button_until: Option<String>,
    #[serde(rename = "showSupportBadge", skip_serializing_if = "Option::is_none")]
    pub show_support_badge: Option<bool>,
}

impl PurchaseUpdate {
    pub fn new() -> PurchaseUpdate {
        PurchaseUpdate {
            hide_buy_button_until: None,
            show_support_badge: None,
        }
    }
}

