/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StackUpdateDto {
    #[serde(rename = "primaryAssetId", skip_serializing_if = "Option::is_none")]
    pub primary_asset_id: Option<uuid::Uuid>,
}

impl StackUpdateDto {
    pub fn new() -> StackUpdateDto {
        StackUpdateDto {
            primary_asset_id: None,
        }
    }
}

