/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagBulkAssetsDto {
    #[serde(rename = "assetIds")]
    pub asset_ids: Vec<uuid::Uuid>,
    #[serde(rename = "tagIds")]
    pub tag_ids: Vec<uuid::Uuid>,
}

impl TagBulkAssetsDto {
    pub fn new(asset_ids: Vec<uuid::Uuid>, tag_ids: Vec<uuid::Uuid>) -> TagBulkAssetsDto {
        TagBulkAssetsDto {
            asset_ids,
            tag_ids,
        }
    }
}

