/*
 * Immich
 *
 * Immich API
 *
 * The version of the OpenAPI document: 1.113.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagsUpdate {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "sidebarWeb", skip_serializing_if = "Option::is_none")]
    pub sidebar_web: Option<bool>,
}

impl TagsUpdate {
    pub fn new() -> TagsUpdate {
        TagsUpdate {
            enabled: None,
            sidebar_web: None,
        }
    }
}

